spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
spring.datasource.username: root
spring.datasource.password: 12345
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.show_sql: folse
spring.jpa.properties.hibernate.use_sql_comments: folse
spring.jpa.properties.hibernate.format_sql: folse


#
#global:
#    settings:
#        - code: MULTIUSER_MODE
#          name: Многопользовательский режим
#          value: 'NO'
#        - code: POST_PREMODERATION
#          name: Премодерация постов
#          value: 'NO'
#        - code: STATISTICS_IS_PUBLIC
#          name: Показывать всем статистику блога
#          value: 'YES'


blog:
    header:
        title: Social
        subtitle: Рассказы разработчиков
        phone: +7 904-884-24-38
        email: 9824104901@mail.ru
        copyright: Михаил Андриевских
        copyrightFrom: 2021

captcha.deleteAfterMin: 60

support.email: anmiha0672@mail.ru
spring.mail.host: smtp.gmail.ru
spring.mail.username: 9824104901
spring.mail.password: Inffg
spring.mail.port: 465
spring.mail.protocol: smtp


spring.servlet.multipart:
  max-file-size: 200KB
  max-request-size: 200KB

spring.mail:
  host: smtp.gmail.com
  username: defdevblog@gmail.com
  password: 12
  port: 587
  smtp.auth: true
  protocol: smtp

mail.debug: true

server.port: ${PORT:8080}

captcha:
  updateTime: 1
  image:
    width: 100
    height: 35

app:
  upload-path: upload/
# hostname: ${HOSTNAME}